apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-red
  labels:
    app.kubernetes.io/name: node-red
    app.kubernetes.io/instance: node-red
    app.kubernetes.io/version: "3.1.3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-red
subjects:
  - kind: ServiceAccount
    name: node-red
    namespace: "default"
